/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_SiTaxi_WRAP_H_
#define SWIG_SiTaxi_WRAP_H_

namespace Swig {
  class Director;
}


struct SwigDirector_BWProactiveHandler : public si_taxi::BWProactiveHandler, public Swig::Director {

public:
    SwigDirector_BWProactiveHandler(VALUE self, si_taxi::BWSim &sim);
    virtual ~SwigDirector_BWProactiveHandler();
    virtual void init();
    virtual void handle_pax_served(size_t empty_origin);
    virtual void handle_idle(si_taxi::BWVehicle &veh);
    virtual void handle_strobe();
};


struct SwigDirector_SarsaActor : public si_taxi::SarsaActor, public Swig::Director {

public:
    SwigDirector_SarsaActor(VALUE self, si_taxi::TabularSarsaSolver &solver);
    virtual ~SwigDirector_SarsaActor();
    virtual void select_action(si_taxi::TabularSarsaSolver::sa_t &sa);
};


#endif
